//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoubleDeckerBar.Adapters
{
    
    public class IMessageEntryViewToContractAddInAdapter : System.AddIn.Pipeline.ContractBase, Start9.Api.Contracts.IMessageEntryContract
    {
        private DoubleDeckerBar.Views.IMessageEntry _view;
        private System.Collections.Generic.Dictionary<Start9.Api.Contracts.IMessageEventHandlerContract, System.EventHandler<DoubleDeckerBar.Views.MessageReceivedEventArgs>> MessageSent_handlers;
        public IMessageEntryViewToContractAddInAdapter(DoubleDeckerBar.Views.IMessageEntry view)
        {
            _view = view;
            MessageSent_handlers = new System.Collections.Generic.Dictionary<Start9.Api.Contracts.IMessageEventHandlerContract, System.EventHandler<DoubleDeckerBar.Views.MessageReceivedEventArgs>>();
        }
        public System.Type MessageObjectType
        {
            get
            {
                return _view.MessageObjectType;
            }
        }
        public string FriendlyName
        {
            get
            {
                return _view.FriendlyName;
            }
        }
        public virtual void MessageSentEventAdd(Start9.Api.Contracts.IMessageEventHandlerContract handler)
        {
            System.EventHandler<DoubleDeckerBar.Views.MessageReceivedEventArgs> adaptedHandler = new System.EventHandler<DoubleDeckerBar.Views.MessageReceivedEventArgs>(new DoubleDeckerBar.Adapters.IMessageEventHandlerContractToViewAddInAdapter(handler).Handler);
            _view.MessageSent += adaptedHandler;
            MessageSent_handlers[handler] = adaptedHandler;
        }
        public virtual void MessageSentEventRemove(Start9.Api.Contracts.IMessageEventHandlerContract handler)
        {
            System.EventHandler<DoubleDeckerBar.Views.MessageReceivedEventArgs> adaptedHandler;
            if (MessageSent_handlers.TryGetValue(handler, out adaptedHandler))
            {
                MessageSent_handlers.Remove(handler);
                _view.MessageSent -= adaptedHandler;
            }
        }
        internal DoubleDeckerBar.Views.IMessageEntry GetSourceView()
        {
            return _view;
        }
    }
}

